version: "3.9"

services:
  web:
    image: django-docker:0.0.1
    build: .
    ports:
      - "8000:8000"
    command: python3 /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      DB_NAME: ecommerce
      DB_USER: admin
    depends_on:
      - db

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
